config/routes.rb
Rails.application.routes.draw do

  devise_for :rootadmins, controllers: {
      sessions: "rootadmins/sessions",
      registrations: "rootadmins/registrations",
      unlocks: "rootadmins/unlocks",
      passwords: "rootadmins/passwords",
      omniauth: "rootadmins/omniauth",
      confirmations: "rootadmins/confirmations"
  } do
  end

  devise_scope :rootadmin do
    get "/rootadmins" => "rootadmins/sessions#new"
  end


  resources :feeds, except: [:index, :show]
  root 'welcome#index'

  namespace :search do
    get 'autocomplete'
    get 'result'
  end

  resources :catalogs
  get 'catalog/:name', to: 'catalogs#show', as: 'showcatalog'

  resources :companies do
    collection do
      delete 'delete_attachment'
    end
  end
  post 'companies/form_render'


  get 'adminpanel', to: 'adminpanel#index'
  get 'feedback', to: 'welcome#feedback', as: 'feedback'
  get 'reklama', to: 'welcome#reklama', as: 'reklama'
  get 'about', to: 'welcome#about', as: 'about'
  get 'sitemap', to: 'welcome#sitemap', as: 'sitemap'

  namespace :adminpanel do
    get 'categories'
    get 'twocategories'
    get 'posts'
    get 'comments'
    get 'twocomments'
    get 'catalogs'
    get 'companies'
    get 'feedback'
  end

  resources :categories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:name', to: 'categories#show', as: 'showcategory'

  resources :twocategories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:category_name/:name', to: 'twocategories#show', as: 'showtwocategory'

  resources :posts, except: [:index] do
    collection do
      post 'like_post'
      delete 'delete_attachment'
    end
  end
  get 'post/:name', to: 'posts#show', as: 'showpost'
  post 'posts/form_render'

  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :twocomments, only: [:edit, :create, :update, :destroy]
end

app/controllers/adminpanel_controller.rb
class AdminpanelController < ApplicationController
  before_action :authenticate_rootadmin!
  skip_before_action :cat
  layout 'adminpanel'

  def index
    @post = Post.count
    @category = Category.count
    @twocategory = Twocategory.count
    @comment = Comment.count
    @commentnew = Comment.where(moderation: 0).count
    @twocomment = Twocomment.count
    @twocommentnew = Twocomment.where(moderation: 0).count
    @catalog = Catalog.count
    @company = Company.count
    @companynew = Company.where(moderation: 0).count
    @feed = Feed.count
    @feednew = Feed.where(moderation: 0).count
  end

  def categories
    @category = Category.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
  end

  def twocategories
    @twocategory = Twocategory.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
  end

  def posts
    @post = Post.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
  end

  def comments
    @comment = Comment.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
    @sort = params[:moderation]
    if @sort == 'all'
      @comment
    elsif @sort
      @comment = Comment.where(moderation: params[:moderation]).paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
    end
  end

  def twocomments
    @twocomment = Twocomment.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
    @sort = params[:moderation]
    if @sort == 'all'
      @twocomment
    elsif @sort
      @twocomment = Twocomment.where(moderation: params[:moderation]).paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
    end
  end

  def catalogs
    @catalogs = Catalog.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
  end

  def companies
    @companies = Company.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
  end

  def feedback
    @feed = Feed.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
    @sort = params[:moderation]
    if @sort == 'all'
      @feed
    elsif @sort
      @feed = Feed.where(moderation: params[:moderation]).paginate(:page => params[:page], :per_page => 20).order(created_at: :desc)
    end
  end


end

app/helpers/adminpanel_helper.rb
module AdminpanelHelper
end

app/views/adminpanel/catalogs.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="container-fluid">
      <% if flash[:alert] %>
          <div class="alert alert-error" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alert alert-info" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>
      <div class="row">
        <div class="col-lg-12">
          <center><%= link_to 'Создать каталог фирмы', new_catalog_path, class: 'btn btn-info btn-lg buttonNew' %></center>
          <section class="panel">
            <header class="panel-heading">
              Таблица Каталогов
            </header>

            <table class="table table-striped table-advance table-hover">
              <tbody>
              <tr>
                <th># id</th>
                <th><i class="icon_pencil"></i> Название</th>
                <th><i class="icon_calendar"></i> Создан</th>
              </tr>
              <% @catalogs.each do |catalog| %>
                  <tr id="product_<%= catalog.id %>">
                    <td><%= catalog.id %></td>
                    <td><%= catalog.name %></td>
                    <td><%= catalog.created_at.strftime('%F') %></td>
                    <td>
                      <div class="btn-group">
                        <%= link_to '<i class="icon_pencil"></i>'.html_safe, edit_catalog_path(catalog.id), class: 'btn btn-success' %>
                        <span class='btn btn-danger deleteMessage2' accon='catalogs' orr_id='<%= catalog.id %>'><i class="icon_close_alt2"></i></span>
                      </div>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </section>
          <p><%= will_paginate @catalogs, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %></p>
        </div>
      </div>
  </section>
</section>

<style>
  .catalogs, .catalogs a{
    background: #2e3b46;
    color: white !important;
  }
</style>

app/views/adminpanel/categories.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="container-fluid">
      <% if flash[:alert] %>
          <div class="alert alert-error" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alert alert-info" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>
    <div class="row">
      <div class="col-lg-12">
        <center><%= link_to 'Создать категорию', new_category_path, class: 'btn btn-info btn-lg buttonNew' %></center>
        <section class="panel">
          <header class="panel-heading">
            Таблица Категорий
          </header>

          <table class="table table-striped table-advance table-hover">
            <tbody>
            <tr>
              <th># id</th>
              <th><i class="icon_image"></i> Картинка</th>
              <th><i class="icon_pencil"></i> Название</th>
              <th><i class="icon_calendar"></i> Создан</th>
            </tr>
            <% @category.each do |category| %>
                <tr id="product_<%= category.id %>">
                  <td><%= category.id %></td>
                  <td><span class="profile-ava sellerAvatar"><%= image_tag category.image %></span></td>
                  <td><%= category.name %></td>
                  <td><%= category.created_at.strftime('%F') %></td>
                  <td>
                    <div class="btn-group">
                      <%= link_to '<i class="icon_pencil"></i>'.html_safe, edit_category_path(category.id), class: 'btn btn-success' %>
                      <span class='btn btn-danger deleteMessage2' accon='categories' orr_id='<%= category.id %>'><i class="icon_close_alt2"></i></span>
                    </div>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </section>
        <p><%= will_paginate @category, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %></p>
      </div>
    </div>
  </section>
</section>

<style>
  .cat, .cat a{
    background: #2e3b46;
    color: white !important;
  }
</style>

app/views/adminpanel/comments.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="container-fluid">
      <% if flash[:alert] %>
          <div class="alert alert-error" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alert alert-info" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <div class="row">
        <div class="wrapDrop">

          <div class="dropdown">
            <a class="btn btn-primary active adminDropMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
              <i class="fa fa-caret-down" aria-hidden="true"></i>
              <% case @sort %>
              <% when '0' %>
                  <%= 'Не прошедшие модерацию' %>
              <% when '1' %>
                  <%= 'Прошедшие модерацию' %>
              <% when 'all' %>
                  <%= 'Все товары' %>
              <% else %>
                  <%= 'Сртировать комментарии по:' %>
              <% end %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="people_btn">
              <li>
                <%= link_to 'Прошедшие модеацию', adminpanel_comments_path(moderation: 1) %>
              </li>
              <li>
                <%= link_to 'Не прошедшие модерацию', adminpanel_comments_path(moderation: 0) %>
              </li>
              <li>
                <%= link_to 'Все комментарии', adminpanel_comments_path(moderation: 'all') %>
              </li>
            </ul>

          </div>
        </div>
      </div>
    </div>

      <div class="row">
        <div class="col-lg-12">
          <section class="panel">
            <header class="panel-heading">
              Таблица Статей
            </header>

            <table class="table table-striped table-advance table-hover">
              <tbody>
              <tr>
                <th class='customIdTh'># id</th>
                <th><i class="icon_pencil"></i> Название статьи</th>
                <th><i class="fa fa-align-left" aria-hidden="true"></i> Комментарий</th>
                <th><i class="icon_calendar"></i> Создан</th>
                <th><i class="icon_key"></i></th>
              </tr>
              <% @comment.each do |comment| %>
                  <tr id="product_<%= comment.id %>">
                    <td><%= comment.id %></td>
                    <td><%= link_to comment.post.name, post_path(comment.post), target: '_blank' %></td>
                    <td><%= link_to((truncate comment.body, length: 100), post_path(comment.post)+"#commId_#{comment.id}", target: '_blank') %></td>
                    <td class="lastTd"><%= comment.created_at.strftime('%F') %></td>
                    <td><%= comment.moderation == 1 ? '<i class="icon_lock-open seller_lock-open">'.html_safe : '<i class="icon_lock seller_lock-lock">'.html_safe %></td>
                    <td>
                      <div class="btn-group tableTools">
                        <%= link_to '<i class="icon_pencil"></i>'.html_safe, edit_comment_path(comment.id), class: 'btn btn-success' %>
                        <span class='btn btn-danger deleteMessage2' accon='comments' orr_id='<%= comment.id %>'><i class="icon_close_alt2"></i></span>
                      </div>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </section>
          <p><%= will_paginate @comment, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %></p>
        </div>
      </div>
  </section>
</section>

<style>
  .comment, .comment a{
    background: #2e3b46;
    color: white !important;
  }
</style>

app/views/adminpanel/feedback.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="container-fluid">
      <% if flash[:alert] %>
          <div class="alert alert-error" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alert alert-info" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <div class="row">
        <div class="wrapDrop">

          <div class="dropdown">
            <a class="btn btn-primary active adminDropMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
              <i class="fa fa-caret-down" aria-hidden="true"></i>
              <% case @sort %>
              <% when '0' %>
                  <%= 'Непрочитанные' %>
              <% when '1' %>
                  <%= 'Прочитанные' %>
              <% when 'all' %>
                  <%= 'Все письма' %>
              <% else %>
                  <%= 'Сртировать письма по:' %>
              <% end %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="people_btn">
              <li>
                <%= link_to 'Прочитанные', adminpanel_feedback_path(moderation: 1) %>
              </li>
              <li>
                <%= link_to 'Непрочитанные', adminpanel_feedback_path(moderation: 0) %>
              </li>
              <li>
                <%= link_to 'Все письма', adminpanel_feedback_path(moderation: 'all') %>
              </li>
            </ul>

          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            Таблица Статей
          </header>

          <table class="table table-striped table-advance table-hover">
            <tbody>
            <tr>
              <th class='customIdTh'># id</th>
              <th><i class="icon_profile"></i> Имя</th>
              <th><i class="icon_mail"></i> Email</th>
              <th><i class="icon_pencil"></i> Заголовок письма</th>
              <th><i class="fa fa-align-left" aria-hidden="true"></i> Сообщение</th>
              <th><i class="icon_calendar"></i> Создан</th>
              <th><i class="icon_key"></i></th>
            </tr>
            <% @feed.each do |feed| %>
                <tr id="product_<%= feed.id %>">
                  <td><%= feed.id %></td>
                  <td><%= feed.name %></td>
                  <td><%= feed.email %></td>
                  <td><%= feed.title %></td>
                  <td><%= truncate feed.description, length: 100 %></td>
                  <td class="lastTd"><%= feed.created_at.strftime('%F') %></td>
                  <td><%= feed.moderation == 1 ? '<i class="icon_check seller_lock-open">'.html_safe : '<i class="icon_check seller_lock-lock">'.html_safe %></td>
                  <td>
                    <div class="btn-group tableTools">
                      <%= link_to '<i class="icon_pencil"></i>'.html_safe, edit_feed_path(feed), class: 'btn btn-success' %>
                      <span class='btn btn-danger deleteMessage2' accon='feeds' orr_id='<%= feed.id %>'><i class="icon_close_alt2"></i></span>
                    </div>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </section>
        <p><%= will_paginate @feed, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %></p>
      </div>
    </div>
  </section>
</section>

<style>
  .feedback, .feedback a{
    background: #2e3b46;
    color: white !important;
  }
</style>

app/views/adminpanel/index.html.erb
<section id="main-content">
  <section class="wrapper">
    <!--overview start-->
    <div class="row">
      <div class="col-lg-12">
        <h3 class="page-header"><i class="fa fa-laptop"></i> Dashboard</h3>
        <ol class="breadcrumb">
          <li><i class="fa fa-home"></i><a href="/">Home</a></li>
          <li><i class="fa fa-laptop"></i>Dashboard</li>
        </ol>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_posts_path do %>
            <div class="info-box brown-bg">
              <i class="icon_document" aria-hidden="true"></i>
              <div class="count"><%= @post %></div>
              <div class="title">Статьи</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_categories_path do %>
            <div class="info-box blue-bg">
              <i class="icon_folder-open" aria-hidden="true"></i>
              <div class="count"><%= @category %></div>
              <div class="title">Категории</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_twocategories_path do %>
            <div class="info-box dark-bg">
              <i class="icon_folder" aria-hidden="true"></i>
              <div class="count"><%= @twocategory %></div>
              <div class="title">Подкатегории</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_comments_path do %>
            <div class="info-box brown-bg">
              <i class="icon_comment" aria-hidden="true"></i>
              <div class="count"><%= @comment %> <span style="color: limegreen ;"><%= "(#{@commentnew})" if @commentnew > 0 %></span></div>
              <div class="title">Комментарии</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_twocomments_path do %>
            <div class="info-box blue-bg">
              <i class="icon_comment" aria-hidden="true"></i>
              <div class="count"><%= @twocomment %> <span style="color: limegreen ;"><%= "(#{@twocommentnew})" if @twocommentnew > 0 %></span></div>
              <div class="title">Комментарии_<span style="font-size: 14px">2</span></div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_catalogs_path do %>
            <div class="info-box dark-bg">
              <i class="icon_tag" aria-hidden="true"></i>
              <div class="count"><%= @catalog %></div>
              <div class="title">Каталоги</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_companies_path do %>
            <div class="info-box brown-bg">
              <i class="icon_briefcase" aria-hidden="true"></i>
              <div class="count"><%= @company %> <span style="color: limegreen ;"><%= "(#{@companynew})" if @companynew > 0 %></span></div>
              <div class="title">Компании</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

      <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <%= link_to adminpanel_feedback_path do %>
            <div class="info-box blue-bg">
              <i class="icon_mail" aria-hidden="true"></i>
              <div class="count"><%= @feed %> <span style="color: limegreen ;"><%= "(#{@feednew})" if @feednew > 0 %></span></div>
              <div class="title">Письма</div>
            </div><!--/.info-box-->
        <% end %>
      </div><!--/.col-->

    </div><!--/.row-->

  </section>


  <style>
    .indexMain, .indexMain a{
      background: #2e3b46;
      color: white !important;
    }
  </style>

app/views/adminpanel/posts.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="container-fluid">
      <% if flash[:alert] %>
          <div class="alert alert-error" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alert alert-info" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <div class="row">
        <div class="col-lg-12">
          <center><%= link_to 'Создать статью', new_post_path, class: 'btn btn-info btn-lg buttonNew' %></center>
          <section class="panel">
            <header class="panel-heading">
              Таблица Статей
            </header>

            <table class="table table-striped table-advance table-hover">
              <tbody>
              <tr>
                <th class='customIdTh'># id</th>
                <th><i class="icon_image"></i> Картинка</th>
                <th><i class="icon_pencil"></i> Название</th>
                <th><i class="fa fa-align-left" aria-hidden="true"></i> Краткое описание</th>
                <th><i class="icon_folder-open_alt"></i> Категории</th>
                <th class="customPodcatTh"><i class="icon_folder-alt"></i> Подкатегории</th>
                <th><i class="icon_calendar"></i> Создан</th>
              </tr>
              <% @post.each do |post| %>
                  <tr id="product_<%= post.id %>">
                    <td><%= post.id %></td>
                    <td class="customTd"><span class="profile-ava sellerAvatar"><%= image_tag post.image.url(:thumb) %></span></td>
                    <td><%= post.name %></td>
                    <td><%= truncate(post.description, length: 200) %></td>
                    <td>
                      <%= post.twocategory.category.name %>
                    </td>
                    <td>
                      <%= post.twocategory.name %>
                    </td>
                    <td class="lastTd"><%= post.created_at.strftime('%F') %></td>
                    <td>
                      <div class="btn-group tableTools">
                        <%= link_to '<i class="icon_pencil"></i>'.html_safe, edit_post_path(post.id), class: 'btn btn-success' %>
                        <span class='btn btn-danger deleteMessage2' accon='posts' orr_id='<%= post.id %>'><i class="icon_close_alt2"></i></span>
                      </div>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </section>
          <p><%= will_paginate @post, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %></p>
        </div>
      </div>
  </section>
</section>

<style>
  .post, .post a{
    background: #2e3b46;
    color: white !important;
  }
</style>

app/views/adminpanel/twocomments.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="container-fluid">
      <% if flash[:alert] %>
          <div class="alert alert-error" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
          <div class="alert alert-info" class="text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
      <% end %>

      <div class="row">
        <div class="wrapDrop">

          <div class="dropdown">
            <a class="btn btn-primary active adminDropMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
              <i class="fa fa-caret-down" aria-hidden="true"></i>
              <% case @sort %>
              <% when '0' %>
                  <%= 'Не прошедшие модерацию' %>
              <% when '1' %>
                  <%= 'Прошедшие модерацию' %>
              <% when 'all' %>
                  <%= 'Все товары' %>
              <% else %>
                  <%= 'Сртировать комментарии2 по:' %>
              <% end %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="people_btn">
              <li>
                <%= link_to 'Прошедшие модеацию', adminpanel_twocomments_path(moderation: 1) %>
              </li>
              <li>
                <%= link_to 'Не прошедшие модерацию', adminpanel_twocomments_path(moderation: 0) %>
              </li>
              <li>
                <%= link_to 'Все комментарии2', adminpanel_twocomments_path(moderation: 'all') %>
              </li>
            </ul>

          </div>
        </div>
      </div>
    </div>

      <div class="row">
        <div class="col-lg-12">
          <section class="panel">
            <header class="panel-heading">
              Таблица Статей
            </header>

            <table class="table table-striped table-advance table-hover">
              <tbody>
              <tr>
                <th class='customIdTh'># id</th>
                <th><i class="icon_pencil"></i> Название статьи</th>
                <th><i class="fa fa-align-left"></i> Комментарий родитель</th>
                <th><i class="fa fa-align-left" aria-hidden="true"></i> Комментарий 2</th>
                <th><i class="icon_calendar"></i> Создан</th>
                <th><i class="icon_key"></i></th>
              </tr>
              <% @twocomment.each do |twocomment| %>
                  <tr id="product_<%= twocomment.id %>">
                    <td><%= twocomment.id %></td>
                    <td><%= link_to twocomment.comment.post.name, post_path(twocomment.comment.post), target: '_blank' %></td>
                    <td><%= link_to((truncate twocomment.comment.body, length: 100), post_path(twocomment.comment.post)+"#commId_#{twocomment.id}", target: '_blank') %></td>
                    <td><%= link_to((truncate twocomment.body, length: 100), post_path(twocomment.comment.post)+"#commId_#{twocomment.id}", target: '_blank') %></td>
                    <td class="lastTd"><%= twocomment.created_at.strftime('%F') %></td>
                    <td><%= twocomment.moderation == 1 ? '<i class="icon_lock-open seller_lock-open">'.html_safe : '<i class="icon_lock seller_lock-lock">'.html_safe %></td>
                    <td>
                      <div class="btn-group tableTools">
                        <%= link_to '<i class="icon_pencil"></i>'.html_safe, edit_twocomment_path(twocomment.id), class: 'btn btn-success' %>
                        <span class='btn btn-danger deleteMessage2' accon='twocomments' orr_id='<%= twocomment.id %>'><i class="icon_close_alt2"></i></span>
                      </div>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </section>
          <p><%= will_paginate @twocomment, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %></p>
        </div>
      </div>
  </section>
</section>

<style>
  .twocomment, .twocomment a{
    background: #2e3b46;
    color: white !important;
  }
</style>