config/routes.rb
Rails.application.routes.draw do

  devise_for :rootadmins, controllers: {
      sessions: "rootadmins/sessions",
      registrations: "rootadmins/registrations",
      unlocks: "rootadmins/unlocks",
      passwords: "rootadmins/passwords",
      omniauth: "rootadmins/omniauth",
      confirmations: "rootadmins/confirmations"
  } do
  end

  devise_scope :rootadmin do
    get "/rootadmins" => "rootadmins/sessions#new"
  end


  resources :feeds, except: [:index, :show]
  root 'welcome#index'

  namespace :search do
    get 'autocomplete'
    get 'result'
  end

  resources :catalogs
  get 'catalog/:name', to: 'catalogs#show', as: 'showcatalog'

  resources :companies do
    collection do
      delete 'delete_attachment'
    end
  end
  post 'companies/form_render'


  get 'adminpanel', to: 'adminpanel#index'
  get 'feedback', to: 'welcome#feedback', as: 'feedback'
  get 'reklama', to: 'welcome#reklama', as: 'reklama'
  get 'about', to: 'welcome#about', as: 'about'
  get 'sitemap', to: 'welcome#sitemap', as: 'sitemap'

  namespace :adminpanel do
    get 'categories'
    get 'twocategories'
    get 'posts'
    get 'comments'
    get 'twocomments'
    get 'catalogs'
    get 'companies'
    get 'feedback'
  end

  resources :categories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:name', to: 'categories#show', as: 'showcategory'

  resources :twocategories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:category_name/:name', to: 'twocategories#show', as: 'showtwocategory'

  resources :posts, except: [:index] do
    collection do
      post 'like_post'
      delete 'delete_attachment'
    end
  end
  get 'post/:name', to: 'posts#show', as: 'showpost'
  post 'posts/form_render'

  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :twocomments, only: [:edit, :create, :update, :destroy]
end

app/models/twocategory.rb
class Twocategory < ApplicationRecord
  belongs_to :category
  has_many :posts, :dependent => :destroy



  has_attached_file :image, :default_url => "noimage.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment_file_name :image, matches: [/png\z/, /jpe?g\z/, /gif\z/]
end

app/controllers/twocategories_controller.rb
class TwocategoriesController < ApplicationController
  before_action :authenticate_rootadmin!, except: [:show]
  before_action :set_twocategory, only: [:edit, :update, :destroy]
  before_action :set_trarslit_twocategory, only: [:show]
  layout 'adminpanel', only: [:new, :edit]

  # GET /twocategories
  # GET /twocategories.json
  def index
    @twocategories = Twocategory.all
  end

  # GET /twocategories/1
  # GET /twocategories/1.json
  def show
    @title = 'Статьи на тему: ' + @twocategory.name
    @categories = Category.all
    @twocategories = Twocategory.where(category_id: @twocategory.category.id)
    @posts = @twocategory.posts.where(visible: 1).paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
  end

  # GET /twocategories/new
  def new
    @twocategory = Twocategory.new
  end

  # GET /twocategories/1/edit
  def edit
  end

  # POST /twocategories
  # POST /twocategories.json
  def create
    @twocategory = Twocategory.new(twocategory_params)

    respond_to do |format|
      if @twocategory.save
        format.html { redirect_to adminpanel_twocategories_path, notice: "Подкатегория #{@twocategory.name} успешно создана" }
        format.json { render :show, status: :created, location: @twocategory }
      else
        format.html { render :new }
        format.json { render json: @twocategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twocategories/1
  # PATCH/PUT /twocategories/1.json
  def update
    respond_to do |format|
      if @twocategory.update(twocategory_params)
        format.html { redirect_to adminpanel_twocategories_path, notice: "Подкатегория #{@twocategory.name} успешно создана" }
        format.json { render :show, status: :ok, location: adminpanel_twocategories_path }
      else
        format.html { render :edit }
        format.json { render json: @twocategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twocategories/1
  # DELETE /twocategories/1.json
  def destroy
    success_response if @twocategory.destroy
  end

  def delete_attachment
    twocategory = Twocategory.find(params[:id])
    twocategory.image = nil
    twocategory.save
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twocategory
      @twocategory = Twocategory.find(params[:id]) or not_found
    end

  def set_trarslit_twocategory
    @category = Category.find_by_translit_url(params[:category_name]) or not_found
    @twocategory = Twocategory.where(category_id: @category, translit_url: params[:name]).first
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twocategory_params
      params.require(:twocategory).permit(:name, :meta_title, :meta_desc, :meta_key, :category_id, :image, :translit_url)
    end
end

app/helpers/twocategories_helper.rb
module TwocategoriesHelper
end

app/views/twocategories/_form.html.erb
<%= form_for(twocategory, :html => {'data-parsley-validate' => true, :class => 'form-horizontal', multipart: true}) do |f| %>
    <% if twocategory.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(twocategory.errors.count, "error") %> prohibited this twocategory from being saved:</h2>

          <ul>
            <% twocategory.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-2 ">
        <%= f.label 'Основное фото', class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <ul class="sliderImg imgcat">
          <li><%= image_tag twocategory.image.url, title: "#{twocategory.name}", id: 'imagePreload', class: "EditImage", height: 100 %></li>
          <li><%= f.file_field :image, id: 'imgInp' %>
            <% unless twocategory.image_file_name.nil? %></li>
                <li><%= link_to("Удалить", {action: :delete_attachment, id: twocategory.id}, method: :delete, data: {confirm: 'Вы уверины что хотите удалить?'}) %></li>
            <% end %>
            </ul>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Имя', class:"control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :name, autofocus: true, class: "form-control form", "required" => true %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Url_translit', class:"control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :translit_url, class: "form-control form", "required" => true %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'МЕТА заголовок', class:"control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :meta_title, class: "form-control form" %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'МЕТА описание', class:"control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_area :meta_desc, class: "form-control form" %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'МЕТА ключи', class:"control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_area :meta_key, class: "form-control form" %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Выберите категорию', class:"control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.select( "category_id", Category.all.collect {|category| [ category.name, category.id ] }, { :include_blank => '- Категории -' }, :class => 'form-control') %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10 actions">
        <br>
        <%= link_to 'Назад', :back, class: 'btn btn-primary' %>
        <button type="submit" class="btn btn-success editSeller">Сохранить</button>
      </div>
    </div>
<% end %>

app/views/twocategories/edit.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            Изменить подкатегорию
          </header>
          <div class="panel-body">
            <%= render 'form', twocategory: @twocategory %>
          </div>
        </section>
      </div>
    </div>
  </section>
</section>

app/views/twocategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twocategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Meta title</th>
      <th>Meta desc</th>
      <th>Meta key</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twocategories.each do |twocategory| %>
      <tr>
        <td><%= twocategory.name %></td>
        <td><%= twocategory.meta_title %></td>
        <td><%= twocategory.meta_desc %></td>
        <td><%= twocategory.meta_key %></td>
        <td><%= twocategory.category %></td>
        <td><%= link_to 'Show', twocategory %></td>
        <td><%= link_to 'Edit', edit_twocategory_path(twocategory) %></td>
        <td><%= link_to 'Destroy', twocategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twocategory', new_twocategory_path %>

app/views/twocategories/new.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            Создать подкатегорию
          </header>
          <div class="panel-body">
            <%= render 'form', twocategory: @twocategory %>
          </div>
        </section>
      </div>
    </div>
  </section>
</section>

app/views/twocategories/show.html.erb
<section class="navCatalog">
  <h1><i class="fa fa-angle-double-right" aria-hidden="true"></i> <%= @twocategory.category.name %><br></h1>
  <ul>
    <% @twocategories.each do |twocategory| %>
        <li <%= raw("class='selectCat'") if @twocategory.id == twocategory.id %>><%= link_to twocategory.name, showtwocategory_path(twocategory.category.translit_url, twocategory.translit_url), title: twocategory.name %></li>
    <% end %>
  </ul>

  <div class="clear"></div>

</section>

<div class="mainWrapBlock">
  <main class="mainBlock">
        <% @posts.each do |post| %>
            <article class="articlePreview">
              <header>
                <h1 class="previewTitle"><%= link_to post.name, showpost_path(post.translit_url), title: post.name %></h1>
              </header>
              <%= link_to showpost_path(post.translit_url) do %>
                  <%= image_tag post.image.url(:preloadMain, timestamp: false), title: post.name, alt: post.name %>
              <% end %>
              <div class="wrapBodyArticle">
                <div class="breadcrumbs"><%= link_to post.twocategory.category.name, showcategory_path(post.twocategory.category.translit_url), title: post.twocategory.category.name %>
                  <i class="fa fa-long-arrow-right" aria-hidden="true" style="color:#C0C0C0; font-size: 10px;"></i>
                  <%= link_to post.twocategory.name, showtwocategory_path(post.twocategory.category.translit_url, post.twocategory.translit_url), title: post.twocategory.name %>
                </div>
                <p><%= post.description %></p>
                <%= link_to 'Читать полностью <i class="fa fa-angle-double-right" aria-hidden="true"></i>'.html_safe, showpost_path(post.translit_url), title: post.name %>
              </div>
              <footer>
                <ul class="infoPost">
                  <li><%= link_to(('<i class="fa fa-comments" aria-hidden="true"></i>').html_safe, showpost_path(post.translit_url)+'#commentBlock', "data-turbolinks" => "false", rel: "nofollow") %> <%= count_comments_post(post) %></li>
                  <% @post = post %>
                  <li id="likePost_<%= post.id %>"><%= render 'posts/like', post: @post %></li>
                  <li><i class="fa fa-eye" aria-hidden="true"></i> <%= post.view_count %></li>
                </ul>
              </footer>
            </article>
        <% end %>
    <div class="clear"></div>
    <%= will_paginate @posts, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %>
  </main>

  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><%= link_to 'Каталог фирм', catalogs_path, title: 'Каталог фирм' %></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li>
              <%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %>
              <% if category.id == @twocategory.category.id %>
                  <ul class="childCategoryRight">
                    <% category.twocategories.each do |twocategory| %>
                        <li><%= link_to twocategory.name, showtwocategory_path(category.translit_url, twocategory.translit_url) %></li>
                    <% end %>
                  </ul>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>