config/routes.rb
Rails.application.routes.draw do

  devise_for :rootadmins, controllers: {
      sessions: "rootadmins/sessions",
      registrations: "rootadmins/registrations",
      unlocks: "rootadmins/unlocks",
      passwords: "rootadmins/passwords",
      omniauth: "rootadmins/omniauth",
      confirmations: "rootadmins/confirmations"
  } do
  end

  devise_scope :rootadmin do
    get "/rootadmins" => "rootadmins/sessions#new"
  end


  resources :feeds, except: [:index, :show]
  root 'welcome#index'

  namespace :search do
    get 'autocomplete'
    get 'result'
  end

  resources :catalogs
  get 'catalog/:name', to: 'catalogs#show', as: 'showcatalog'

  resources :companies do
    collection do
      delete 'delete_attachment'
    end
  end
  post 'companies/form_render'


  get 'adminpanel', to: 'adminpanel#index'
  get 'feedback', to: 'welcome#feedback', as: 'feedback'
  get 'reklama', to: 'welcome#reklama', as: 'reklama'
  get 'about', to: 'welcome#about', as: 'about'
  get 'sitemap', to: 'welcome#sitemap', as: 'sitemap'

  namespace :adminpanel do
    get 'categories'
    get 'twocategories'
    get 'posts'
    get 'comments'
    get 'twocomments'
    get 'catalogs'
    get 'companies'
    get 'feedback'
  end

  resources :categories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:name', to: 'categories#show', as: 'showcategory'

  resources :twocategories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:category_name/:name', to: 'twocategories#show', as: 'showtwocategory'

  resources :posts, except: [:index] do
    collection do
      post 'like_post'
      delete 'delete_attachment'
    end
  end
  get 'post/:name', to: 'posts#show', as: 'showpost'
  post 'posts/form_render'

  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :twocomments, only: [:edit, :create, :update, :destroy]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_welcome
  skip_before_action :cat

  def index
    @posts = Post.where(visible: 1).paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
  end

  def feedback
    @title = 'Обратная связь | ' + @domen
    @feed = Feed.new
    @categorias = Category.all
  end

  def reklama
    @title = 'Реклама на сайте | ' + @domen
    @feed = Feed.new
    @categorias = Category.all
  end

  def about
    @title = 'О проекте - Блогремонта | ' + @domen
    @categorias = Category.all
  end

  def sitemap
    @categories = Category.all
  end


  private

  def set_welcome
    @categories = Category.all
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="mainWrapBlock">
  <main class="mainBlock">
    <article class="articlePreview ">
      <header>
        <h1 class="previewTitle previewContacts"><%= image_tag 'logo-50X29.png', title: 'blogremonta.com', alt: 'blogremonta.com' %> О сайте</h1>
      </header>
      <div class="wrapBodyArticle container-fluid">
        <p class="parAbout">
          <span class="logoSpanAbout">БлогРемонта</span> - это сайт, на котором можно найти ответы на различные интересующие вопросы о ремонте и строительстве.  Как правильно сделать <a href="/category/remont-v-kvartire" title="ремонт в квартире">ремонт в квартире</a>, обустроить <a href="/category/remont-v-kvartire/balkon" title="балкон">балкон</a>, ванную комнату, <a href="category/remont-v-kvartire/Kukhnya" title="кухня">кухню</a> – обо всем этом очень просто узнать, посетив наш сайт. Выполнить <a href="/category/stroitelstvo-doma" title="строительство дома">строительство дома</a> самостоятельно сумеет даже новичок, если будет придерживаться рекомендаций указанных на сайте.</p>

        <p class="parAbout">Провести наружные отделочные работы вместе с Блогремонта также не сложно. У нас представлена подробная информация о том, как правильно обустроить <a title="Фундамент" href="/category/stroitelstvo-doma/fundament">фундамент</a>, <a title="Крыша" href="/category/stroitelstvo-doma/krysha">крышу</a>, <a title="Цоколь" href="/category/stroitelstvo-doma/tsokol">цоколь</a> и многое другое.  Сделать любой вид ремонтных работ на уровне, возможно только используя качественные материалы. Мы готовы ознакомить наших читателей и с этим вопросом, посоветовав проверенные марки и строительные материалы. </p>

        <p class="parAbout">Ни один ремонт не обойдется без качественно оформленного <a href="/category/dizayn-interyera" title="дизайна интерьера">дизайна интерьера</a>. На сайте есть много статей, которые ознакомят читателя с последними новинками и модными веяниями. Оформить интерьер помещения красиво и со вкусом позволят правильно подобранные строительные <a href="/category/instrument" title="инструменты">инструменты</a>.  В каждой статье Блогремонта уделяет внимание этому вопросу. Ознакомившись с советами от опытных специалистов, каждый узнает, на какие материалы и приспособления стоит обратить внимание при выборе.</p>

        <p class="parAbout">Для тех, у кого нет времени делать ремонт самостоятельно мы также нашли выход. Если в силу своей занятости или отсутствия опыта читатель не готов проводить работы самостоятельно, то стоит посетить наш <a title="Каталог фирм" class="catFirms" href="/catalogs">каталог фирм и компаний</a> .  Блогремонта предлагает ознакомиться со списком проверенных подрядчиков, которые с радостью возьмут хлопоты по ремонту на себя. В каталоге представлен большой перечень зарегистрированных компаний с различной ценовой политикой. Заручившись поддержкой профессионалов, будет не сложно справиться с ремонтными работами любой сложности.</p>

        <p class="parAbout">Строительный сайт Блогремонта – это место, где представлена вся необходимая информация о ремонте и дизайне интерьера. Вместе с нами делать ремонт всегда проще!</p>
      </div>
    </article>
  </main>

  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><%= link_to 'Каталог фирм', catalogs_path, title: 'Каталог фирм' %></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li>
              <%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>

app/views/welcome/feedback.html.erb
<div class="mainWrapBlock">
  <main class="mainBlock">
    <article class="articlePreview contactsWrap">
      <header>
        <h1 class="previewTitle previewContacts"><i class="fa fa-envelope-o" aria-hidden="true"></i> Написать нам</h1>
      </header>
      <div class="wrapBodyArticle container-fluid">
        <p class="contactPrew">Связаться с нами, можно написав на e-mail:
          <a href="mailto:info@gidremonta.com">info@blogremonta.com</a> или же через форму обратной связи:<br>
          <noindex>
            <nofollow></nofollow>
          </noindex>
        </p>
        <div class="note noteContacts">
          <span class="noteSpan">Внимание:</span> все поля формы обязательны для заполнения.
        </div>
        <div class="feedback"></div>
        <%= form_for @feed, html: {:class => 'contactsForm row', :remote => true, onsubmit: "sendAnimate('.commitsSubmit')"} do |f| %>

            <div class="inputFloat oneInput col-xs-12 col-sm-6">
              <%= f.text_field :name, placeholder: 'Имя', required: true %>
            </div>
            <div class="inputFloat twoInput col-xs-12 col-sm-6">
              <%= f.text_field :email, placeholder: 'Email', required: true %>
            </div>
            <div class="inputFloat lineInput col-xs-12">
              <%= f.text_field :title, placeholder: 'Тема', required: true %>
            </div>
            <%= f.text_area :description, class: 'col-xs-12', placeholder: 'Ваше сообщение', rows: 2, maxlength: 2000, required: true %>
            <%= f.button 'Отправить', class: 'commitsSubmit col-xs-12' %>
        <% end %>
      </div>
    </article>
  </main>

  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><%= link_to 'Каталог фирм', catalogs_path, title: 'Каталог фирм' %></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li>
              <%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>

<style>
  .navVaries .feedPage{
    border-color:  #CA1B18;
  }
</style>

app/views/welcome/index.html.erb
<div class="mainWrapBlock">
  <main class="mainBlock">
    <% @posts.each do |post| %>
        <article class="articlePreview">
          <header>
            <h1 class="previewTitle"><%= link_to post.name, showpost_path(post.translit_url), title: post.name %></h1>
          </header>
          <%= link_to showpost_path(post.translit_url) do %>
              <%= image_tag post.image.url(:preloadMain, timestamp: false), title: post.name, alt: post.name %>
          <% end %>
          <div class="wrapBodyArticle">
            <div class="breadcrumbs"><%= link_to post.twocategory.category.name, showcategory_path(post.twocategory.category.translit_url), title: post.twocategory.category.name %>
              <i class="fa fa-long-arrow-right" aria-hidden="true" style="color:#C0C0C0; font-size: 10px;"></i>
              <%= link_to post.twocategory.name, showtwocategory_path(post.twocategory.category.translit_url, post.twocategory.translit_url), title: post.twocategory.name %>
            </div>
              <p><%= post.description %></p>
            <%= link_to 'Читать полностью <i class="fa fa-angle-double-right" aria-hidden="true"></i>'.html_safe, showpost_path(post.translit_url), title: post.name %>
          </div>
          <footer>
            <ul class="infoPost">
              <li><%= link_to(('<i class="fa fa-comments" aria-hidden="true"></i>').html_safe, showpost_path(post.translit_url)+'#commentBlock', "data-turbolinks" => "false", rel: "nofollow") %> <%= count_comments_post(post) %></li>
              <% @post = post %>
              <li id="likePost_<%= post.id %>"><%= render 'posts/like', post: @post %></li>
              <li><i class="fa fa-eye" aria-hidden="true"></i> <%= post.view_count %></li>
            </ul>
          </footer>
        </article>
    <% end %>
    <div class="clear"></div>

    <%= will_paginate @posts, previous_label: '<i class="fa fa-chevron-circle-left fa-lg adminPag"></i>'.html_safe, next_label: '<i class="fa fa-chevron-circle-right fa-lg adminPag"></i>'.html_safe %>
  </main>
  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><%= link_to 'Каталог фирм', catalogs_path, title: 'Каталог фирм' %></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li><%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %></li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>


<style>
  .navVaries .mainPage{
    border-color:  #CA1B18;
  }
</style>

app/views/welcome/reklama.html.erb
<div class="mainWrapBlock">
  <main class="mainBlock">
    <article class="articlePreview contactsWrap">
      <header>
        <h1 class="previewTitle previewContacts"><i class="fa fa-info-circle" aria-hidden="true"></i> Реклама на сайте</h1>
      </header>
      <div class="wrapBodyArticle container-fluid">
        <p class="contactPrew reklamaPrew">Администрация  сайта “blogremonta.com” с интересом  рассмотрит предложения и идеи о различных видах взаимовыгодного сотрудничества. Если у Вас возникли вопросы связанные с платным размещением статей и рекламы на нашем сайте, то пишите на e-mail:
          <a href="mailto:info@gidremonta.com">info@blogremonta.com</a> или можете обратиться к нам через форму обратной связи:<br>
          <noindex>
            <nofollow></nofollow>
          </noindex>
        </p>
        <div class="note noteContacts">
          <span class="noteSpan">Внимание:</span> все поля формы обязательны для заполнения.
        </div>
        <div class="feedback"></div>
        <%= form_for @feed, html: {:class => 'contactsForm row', :remote => true, onsubmit: "sendAnimate('.commitsSubmit')"} do |f| %>

            <div class="inputFloat oneInput col-xs-12 col-sm-6">
              <%= f.text_field :name, placeholder: 'Имя', required: true %>
            </div>
            <div class="inputFloat twoInput col-xs-12 col-sm-6">
              <%= f.text_field :email, placeholder: 'Email', required: true %>
            </div>
            <div class="inputFloat lineInput col-xs-12">
              <%= f.text_field :title, placeholder: 'Тема', required: true %>
            </div>
            <%= f.text_area :description, class: 'col-xs-12', placeholder: 'Ваше сообщение', rows: 2, maxlength: 2000, required: true %>
            <%= f.button 'Отправить', class: 'commitsSubmit col-xs-12' %>
        <% end %>
      </div>
    </article>
  </main>

  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><%= link_to 'Каталог фирм', catalogs_path, title: 'Каталог фирм' %></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li>
              <%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>



<style>
  .navVaries .reklamaSites{
    border-color:  #CA1B18;
  }
</style>

app/views/welcome/sitemap.erb
<div class="mainWrapBlock">
  <main>
    <div class="sitemapBlock">
      <h1><i class="fa fa-angle-double-right" aria-hidden="true"></i> Карта сайта<br></h1>
      <div class="wrapNavMap">
        <ul class="parentCatMap">
          <h2>Главное меню:</h2>
          <li><%= link_to 'Каталог фирм', catalogs_path, title: 'Каталог фирм', class: 'catLinkMap' %></li>
          <li><%= link_to 'Реклама на сайте', reklama_url, title: 'Реклама на сайте', class: 'catLinkMap' %></li>
          <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь', class: 'catLinkMap' %></li>
          <li><%= link_to 'О сайте', about_url, title: 'О сайте', class: 'catLinkMap' %></li>
          <li><%= link_to 'Карта сайта', sitemap_url, title: 'Карта сайта', class: 'catLinkMap' %></li>
          <h2>Рубрики сайта:</h2>
          <% @categories.each do |category| %>
              <li>
                <%= link_to category.name, showcategory_path(category.translit_url), class: 'catLinkMap' %>
                <ul class="parentCatMapLeft">
                  <% category.twocategories.each do |twocategory| %>
                      <li><%= link_to twocategory.name, showtwocategory_path(category.translit_url, twocategory.translit_url) %></li>
                      <ul class="parTwo">
                      <% twocategory.posts.each do |post| %>
                            <li>- <%= link_to post.name, showpost_path(post.translit_url) %></li>
                      <% end %>
                      </ul>
                  <% end %>
                </ul>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </main>
</div>