config/routes.rb
Rails.application.routes.draw do

  devise_for :rootadmins, controllers: {
      sessions: "rootadmins/sessions",
      registrations: "rootadmins/registrations",
      unlocks: "rootadmins/unlocks",
      passwords: "rootadmins/passwords",
      omniauth: "rootadmins/omniauth",
      confirmations: "rootadmins/confirmations"
  } do
  end

  devise_scope :rootadmin do
    get "/rootadmins" => "rootadmins/sessions#new"
  end


  resources :feeds, except: [:index, :show]
  root 'welcome#index'

  namespace :search do
    get 'autocomplete'
    get 'result'
  end

  resources :catalogs
  get 'catalog/:name', to: 'catalogs#show', as: 'showcatalog'

  resources :companies do
    collection do
      delete 'delete_attachment'
    end
  end
  post 'companies/form_render'


  get 'adminpanel', to: 'adminpanel#index'
  get 'feedback', to: 'welcome#feedback', as: 'feedback'
  get 'reklama', to: 'welcome#reklama', as: 'reklama'
  get 'about', to: 'welcome#about', as: 'about'
  get 'sitemap', to: 'welcome#sitemap', as: 'sitemap'

  namespace :adminpanel do
    get 'categories'
    get 'twocategories'
    get 'posts'
    get 'comments'
    get 'twocomments'
    get 'catalogs'
    get 'companies'
    get 'feedback'
  end

  resources :categories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:name', to: 'categories#show', as: 'showcategory'

  resources :twocategories, except: [:index] do
    collection do
      delete 'delete_attachment'
    end
  end
  get 'category/:category_name/:name', to: 'twocategories#show', as: 'showtwocategory'

  resources :posts, except: [:index] do
    collection do
      post 'like_post'
      delete 'delete_attachment'
    end
  end
  get 'post/:name', to: 'posts#show', as: 'showpost'
  post 'posts/form_render'

  resources :comments, only: [:edit, :create, :update, :destroy]
  resources :twocomments, only: [:edit, :create, :update, :destroy]
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, :presence => {message: 'укажите своё имя'}
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'указан не корректный Email'
  validates :state, :presence => {message: 'укажите свою страну'}
  validates :city, :presence => {message: 'укажите свою область'}
  validates_inclusion_of :state, :in => Catalog::STATE_TYPES + [''], :message => 'Выбран не верный формат страны'
  validates :description, :presence => {message: 'укажите краткое описание компании'}
  validates :company_skills, :presence => {message: 'выберите каталог'}

  has_attached_file :image, :styles => {:original => "16x" }, :default_url => "no-logo-company.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :company_skills, :dependent => :destroy
  accepts_nested_attributes_for :company_skills,
                                :allow_destroy => true,
                                :reject_if => :all_blank

  def to_param
    "#{id}-#{name.parameterize}"
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_rootadmin!, except: [:show, :new, :create, :form_render]
  before_action :set_company, only: [:edit, :update, :destroy]
  before_action :set_regular, only: [:show]
  layout 'adminpanel', only: [:edit]
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    cat_name = []
    @title = 'Компания: ' + @company.name
    @description ="#{@company.name}, #{@company.state}, полная информация о компании"
    @company.company_skills.each{|skill| cat_name << skill.catalog.name}
    @keywords = cat_name.join(', ')
    @catalogs = Catalog.all
  end

  # GET /companies/new
  def new
    @title = 'Добавить строительную компанию или фирму в каталог'
    @company = Company.new
    @company.company_skills.build
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create

    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        WlcomeMailer.new_company.deliver
        format.js
      else
        format.js
      end
    end
  end


  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_rootadmin_params)
        format.html { redirect_to adminpanel_companies_path, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end


  def form_render
    if params[:company][:state]
      if params[:company][:state].blank?
        render text: ''
      else
        @state = params[:company][:state]
        render :partial => 'city', locals: { state: @state }
      end
    end

  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    success_response if @company.destroy
  end

  def delete_attachment
    company = Company.find(params[:id])
    company.image = nil
    company.save
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id]) or not_found
    end

  def set_regular
    @company = Company.find(params[:id]) or not_found
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :phone, :email, :site, :description, :state, :city, :adress, :image,
                                      company_skills_attributes: [:id, :_destroy, :catalog_id]
      )
    end

  def company_rootadmin_params
    params.require(:company).permit(:name, :phone, :email, :site, :description, :moderation, :state, :city, :adress, :image,
                                    company_skills_attributes: [:id, :_destroy, :catalog_id]
    )
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_city.html.erb
<div class="inputFloat selectInput col-xs-12">
  <span class="validInput clear">*</span>

  <%= select_tag 'company[city]',  options_for_select(Catalog::CITY_TYPES[state].collect {|city| [city, city]}), {:include_blank => '- Область -', :class => 'post_twocategory_id', required: true} %>
</div>

app/views/companies/_form.html.erb
<%= nested_form_for(company, :html => {:class => 'form-horizontal'}) do |f| %>
    <% if company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(company.errors.count, "error") %> prohibited this catalog from being saved:</h2>

          <ul>
            <% company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <div class="col-sm-2 ">
        <%= f.label 'Основное фото', class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <ul class="sliderImg imgcat">
          <li><%= image_tag company.image, title: "#{company.name}", id: 'imagePreload', class: "EditImage", height: 100 %></li>
          <!-- Trigger -->
          <li><%= f.file_field :image, id: 'imgInp' %>
            <% unless company.image_file_name.nil? %></li>
                <li><%= link_to("Удалить", {action: :delete_attachment, id: company.id}, method: :delete, data: {confirm: 'Вы уверины что хотите удалить?'}) %></li>
            <% end %>
            </ul>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Название', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :name, autofocus: true, class: "form-control form", "required" => true %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Почта', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :email, class: "form-control form", "required" => true %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Сайт', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :site, class: "form-control form" %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Телефон', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :phone, class: "form-control form" %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Страна', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :state, class: "form-control form", "required" => true %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Область', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :city, class: "form-control form", "required" => true %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Адрес', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :adress, class: "form-control form" %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Описание', class: "control-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_area :description, class: "form-control form", "required" => true, rows: 6 %>
      </div>
    </div>

    <div class="form-group">
      <div class=" col-sm-2">
        <%= f.label 'Категории', class: "control-label" %>
      </div>
      <div class="col-sm-10">
        <%= f.fields_for :company_skills do |skill| %>
            <div class="wrapCatCom">
              <%= skill.select(:catalog_id, options_for_select(Catalog.all.collect { |catalog| [catalog.name, catalog.id] }, skill.object.catalog_id), {prompt: '- Выберите каталог -'}, class: "form-control form", required: true) %>
              <%= skill.link_to_remove '<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, class: 'deleteInput' %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 ">
        <%= f.label 'Модерация компании', for: 'moderation' %>
      </div>
      <div class="col-sm-10">
      <%= f.check_box :moderation, id: 'moderation' %>
    </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10 actions">
        <br>
        <%= link_to 'Назад', adminpanel_companies_path, class: 'btn btn-primary' %>
        <button type="submit" class="btn btn-success editSeller">Сохранить</button>
      </div>
    </div>
<% end %>

app/views/companies/create.js.erb
<% if @company.save %>
$('.contactsForm input[type=text]').val('');
$('.contactsForm textarea').val('');
$('.contactsForm select').val('');
$('.contactsForm').remove();
$('.note').remove();
$('.commentFlash').remove();

$('.companyCatalog').append("<h3 class='commentFlash'>Ваша компания будет добавлена в наш каталог после проверки модератормом</h3>");

<% else %>
$('.companyCatalog').append("<h3 class='commentFlash' style='color: red;'><%= @company.errors.messages.values.join(', ') %></h3>");
<% end %>

app/views/companies/edit.html.erb
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            Изменить компанию
          </header>
          <div class="panel-body">
            <%= render 'form', company: @company %>
          </div>
        </section>
      </div>
    </div>
  </section>
</section>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Site</th>
      <th>Description</th>
      <th>State</th>
      <th>City</th>
      <th>Moderation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.phone %></td>
        <td><%= company.email %></td>
        <td><%= company.site %></td>
        <td><%= company.description %></td>
        <td><%= company.state %></td>
        <td><%= company.city %></td>
        <td><%= company.moderation %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<div class="mainWrapBlock">
  <main class="mainBlock">
    <article class="articlePreview contactsWrap">
      <header>
        <h1 class="previewTitle previewContacts"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Добавить компанию в каталог</h1>
      </header>
      <div class="wrapBodyArticle container-fluid">
        <div class="note noteContacts">
          <span class="noteSpan">Внимание:</span> все поля формы с пометкой <span class="noteValid"> * </span> обязательны для заполнения.
        </div>
        <div class="companyCatalog"></div>
        <%= nested_form_for @company, html: {class: 'contactsForm', multipart: true, onsubmit: "sendAnimate('.commitsSubmit')" }, remote: true  do |f| %>
            <% if @company.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

                  <ul>
                    <% @company.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <div class="inputFloat lineInput col-xs-12 logoCom">
              <span>Логотип компании:</span>
            <%= f.file_field :image, placeholder: 'sa' %>
            </div>
            <div class="inputFloat oneInput col-xs-12 col-sm-6">
              <span class="validInput">*</span>
              <%= f.text_field :name, placeholder: 'Название компании', required: true %>
            </div>
            <div class="inputFloat twoInput col-xs-12 col-sm-6">
              <span class="validInputTwo">*</span>
              <%= f.text_field :email, placeholder: 'Email', required: true %>
            </div>
            <div class="inputFloat oneInput col-xs-12 col-sm-6">
              <%= f.text_field :site, placeholder: 'Сайт' %>
            </div>
            <div class="inputFloat twoInput col-xs-12 col-sm-6">
              <%= f.text_field :phone, placeholder: 'Телефон' %>
            </div>
            <div class="inputFloat selectInput col-xs-12">
              <span class="validInput">*</span>
              <%= select_tag 'company[state]', options_for_select(Catalog::STATE_TYPES.collect{|state| [state, state, class: 'inputSelected']}, @state), {:include_blank => '- Укажите вашу страну -', :class => 'form-control form', :id => 'company_city', required: true} %>
            </div>
            <div id="city" ></div>
            <div class="inputFloat lineInput col-xs-12">
              <%= f.text_field :adress, placeholder: 'Город, улица, дом или офис' %>
            </div>
            <div class="inputFloat selectInput col-xs-12">
              <span class="validInput">*</span>
              <%= f.text_area :description, placeholder: 'Краткое описание компании', class: 'col-xs-12', rows: 2, maxlength: 2000, required: true %>
            </div>
            <span class="PrewSelectCatalog">Выбрать не меньше одного <strong>каталога</strong>:</span>
            <%= f.fields_for :company_skills do |skill| %>
                <div class="inputFloat selectInput col-xs-12">
                  <span class="validInput">*</span>
                  <%= skill.select(:catalog_id, options_for_select(Catalog.all.collect{|catalog| [catalog.name, catalog.id]}),  {prompt: '- Выберите каталог -'}, class:"form-control form") %>

                  <%=  skill.link_to_remove '<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, class: 'deleteInput' %>
                </div>
            <% end %>

            <p><center><%= f.link_to_add '- Ещё <i class="fa fa-refresh" aria-hidden="true"></i> -'.html_safe, :company_skills, class: 'addCatOther' %></center></p>

            <%= f.button 'Добавить в каталог', class: 'commitsSubmit col-xs-12' %>
        <% end %>
      </div>
    </article>
  </main>


  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><a href="#">Каталог фирм</a></li>
        <li><a href="#">Реклама на сайте</a></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li>
              <%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>

app/views/companies/show.html.erb
<section class="navCatalog">
  <h1><i class="fa fa-angle-double-right" aria-hidden="true"></i> Каталог строительных компаний:<br></h1>
  <ul>
    <% @catalogs.each do |catalog| %>
        <li><%= link_to catalog.name, showcatalog_path(catalog.translit_url), title: catalog.name %></li>
    <% end %>
  </ul>
  <div class="clear"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="wrapButtonComp col-xs-12">
        <%= link_to 'Добавить компанию в каталог', new_company_path, title: 'Добавить в каталог', class: 'addNewComp' %>
      </div>
    </div>
  </div>
</section>
<div class="mainWrapBlock">
  <main class="mainBlock">
        <article class="companyCat showCat">
          <header>
            <h1><%= image_tag @company.image, alt: @company.name, title: @company.name %> <%= @company.name %></h1>
            <i class="fa fa-globe" aria-hidden="true" style="color: #FF7A00;"></i> <span><%= @company.state %>, <%= @company.city %></span>
          </header>
          <div class="companyDesc">
            <p><strong>Email:</strong> <%= @company.email %></p>
            <p><strong>Сайт:</strong> <%= @company.site %></p>
            <p><strong>Телефон:</strong> <%= @company.phone %></p>
            <p><strong>Адрес:</strong> <%= @company.adress %></p>
            <p class="compDesc"><strong>Описание компании:</strong> <%= @company.description %></p>
          </div>
          <footer>
            <% @company.company_skills.each do |skills| %>
                <%= link_to ('<i class="fa fa-tag" aria-hidden="true" style="color: #767676;"></i> ' + skills.catalog.name).html_safe, showcatalog_path(skills.catalog.translit_url), title: skills.catalog.name %>
            <% end %>
          </footer>
        </article>
    <%= link_to '<i class="fa fa-chevron-left" aria-hidden="true"></i>
 Назад'.html_safe, catalogs_path, title: 'Вернуться к каталогам фирм', class: 'backCatalogs' %>
  </main>
  <aside class="navRightBlock">
    <div class="mainMenuRight">
      <h1>Главное меню</h1>
      <ul>
        <li><a href="/" title='Главная'>Главная</a></li>
        <li><a href="#">Каталог фирм</a></li>
        <li><%= link_to 'Обратная связь', feedback_url, title: 'Обратная связь' %></li>
      </ul>
    </div>
    <div class="CategoryRight">
      <h1>Рубрики сайта</h1>
      <ul class="parentCategoryRight">
        <% @categories.each do |category| %>
            <li><%= link_to category.name, showcategory_path(category.translit_url), class: 'parentLink' %></li>
        <% end %>
      </ul>
    </div>
    <div class="clear"></div>
  </aside>
</div>